### ISSUE TITLE
What is this Slim network based on? Is there a paper on that?

### ISSUE THREAD

**Issue by yxchng** [ainrichman/Peppa-Facial-Landmark-PyTorch#2]

**Comment by ainrichman** [comment]
No paper. It is based on practical experience. Basically, the design comes from MobileNet DetpthWise Convolution

**Comment by kimtaehyeong** [comment]
Hello. 
How can I train using the mobilenet backbone rather than the Slim model? Currently mobileNet cannot find an implementation.
thank you.
