### ISSUE TITLE
Wrong result for landmark

### ISSUE THREAD

**Issue by kafan1986** [ainrichman/Peppa-Facial-Landmark-PyTorch#9]
I am using the model on android and using C++ code to run the model. The result are very incorrect.

![device-2020-06-10-045416](https://user-images.githubusercontent.com/7953422/84210581-b08d6080-aad6-11ea-9c10-b121ed274ef3.png)

**Comment by ainrichman** [comment]
Emm this seems quite unacceptable. Could you please share the details about how you use the model?

**Comment by kafan1986** [comment]
@ainrichman Result is right. There was some issues with my inference code. It is all OK now. Closing the issue.
